### ISSUE TITLE
USER STORY: Easily Navigate and Find Content

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/PP4#1]
As a **visitor**, I want to easily navigate the blog and find content that interests me, so I can quickly access the information I'm looking for.

## Acceptance Criteria: 

- Acceptance Criteria 1: Users can easily find the main navigation menu on the blog.

- Acceptance Criteria 2: Clicking on a category leads to a page displaying related articles.

- Acceptance Criteria 3: Clicking on a blog post leads to a page displaying the full post article.

## Tasks: 

- [ ] Design and implement a clear and prominent navigation menu.
- [ ] Create and style category section that display relevant articles dedicated to the category.
- [ ] Make sure that the navigation menu are responsive and looking good at all devices.
