### ISSUE TITLE
Planning and Documentation

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/PP4#22]
## Tasks: 

- [ ] Plan Sprint (Must do)
- [ ] Create and write readme.md (Must do)
- [ ] Design Database Schema (Should do)
- [ ] Create the wireframes (Should do)

**Comment by KimBergstroem** [comment]
Planning Sprints and user stories with MoSCoW principles done along with creating the readme.
